[build]
builder = "dockerfile"

[deploy]
# Solo ejecuta el binario ya compilado, no necesitas ejecutar migraciones aquí
startCommand = "./main"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
