[build]
builder = "dockerfile"

[deploy]
# Comando modificado para ejecutar las migraciones y luego el binario compilado
startCommand = "./migrate/migrate.go && ./main"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
