[build]
builder = "dockerfile"

[deploy]
# Solo ejecuta el binario ya compilado, no necesitas ejecutar migraciones aquí
#startCommand = "./main"

# Primero ejecutamos las migraciones, luego iniciamos la aplicación
startCommand = "sh -c 'sleep 5 && ./migrate && ./main'"

healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
